version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mitanshpithadia76@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root123
    ports:
      - "5050:80"
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    volumes:
      - C:/Users/Mitansh/OneDrive/Desktop/Internship/learning/oop/18-02-2025/Task/org/src:/app/src
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
volumes:
  postgres-data: